seed: 42

graph_setup: file # random or file

# parameters for random graph generation 
# V: 10 # number of genotypes/nodes

# parameters for file-specified graph setup 
A: data/absfit/absfit_adj.csv

# general parameters
N: 10000 # population size 
timesteps: 500 # number of timesteps
mu: 0.0 # mutation rate

c: 1 # number offspring produced 

num_gens: 10

phenotype_probs_setup: file # random or file

# parameters for file-specified phenotype probability assignment 
pheno_probs: data/absfit/absfit_prgp_probs.csv

repro_probs_setup: file # random or file

# parameters for random repro probability assignment 

# parameters for file-specified repro probability assignment 
repro_probs: data/absfit/absfit_reproprobs.csv


